package C0;

import J0.AbstractC0386b;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: renamed from: C0.f, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes.dex */
abstract class AbstractC0243f {
    private static List a(String str) {
        int length = str.length();
        AbstractC0386b.d(length >= 2, "Invalid path \"%s\"", str);
        if (length == 2) {
            AbstractC0386b.d(str.charAt(0) == 1 && str.charAt(1) == 1, "Non-empty path \"%s\" had length 2", str);
            return Collections.emptyList();
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb = new StringBuilder();
        int i3 = 0;
        while (i3 < length) {
            int iIndexOf = str.indexOf(1, i3);
            if (iIndexOf < 0 || iIndexOf > length2) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            int i4 = iIndexOf + 1;
            char cCharAt = str.charAt(i4);
            if (cCharAt == 1) {
                String strSubstring = str.substring(i3, iIndexOf);
                if (sb.length() != 0) {
                    sb.append(strSubstring);
                    strSubstring = sb.toString();
                    sb.setLength(0);
                }
                arrayList.add(strSubstring);
            } else if (cCharAt == 16) {
                sb.append(str.substring(i3, iIndexOf));
                sb.append((char) 0);
            } else {
                if (cCharAt != 17) {
                    throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
                }
                sb.append(str.substring(i3, i4));
            }
            i3 = iIndexOf + 2;
        }
        return arrayList;
    }

    static D0.u b(String str) {
        return D0.u.A(a(str));
    }

    static String c(D0.e eVar) {
        StringBuilder sb = new StringBuilder();
        int iW = eVar.w();
        for (int i3 = 0; i3 < iW; i3++) {
            if (sb.length() > 0) {
                e(sb);
            }
            d(eVar.t(i3), sb);
        }
        e(sb);
        return sb.toString();
    }

    private static void d(String str, StringBuilder sb) {
        int length = str.length();
        for (int i3 = 0; i3 < length; i3++) {
            char cCharAt = str.charAt(i3);
            if (cCharAt == 0) {
                sb.append((char) 1);
                cCharAt = 16;
            } else if (cCharAt == 1) {
                sb.append((char) 1);
                cCharAt = 17;
            }
            sb.append(cCharAt);
        }
    }

    private static void e(StringBuilder sb) {
        sb.append((char) 1);
        sb.append((char) 1);
    }

    static String f(String str) {
        StringBuilder sb = new StringBuilder(str);
        int length = sb.length() - 1;
        char cCharAt = sb.charAt(length);
        AbstractC0386b.d(cCharAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb.setCharAt(length, (char) (cCharAt + 1));
        return sb.toString();
    }
}
