package com.pulze.pulze;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int activityAction = 0x7f010000;
        public static final int activityName = 0x7f010001;
        public static final int alpha = 0x7f010002;
        public static final int alwaysExpand = 0x7f010003;
        public static final int buttonSize = 0x7f010004;
        public static final int circleCrop = 0x7f010005;
        public static final int clearTop = 0x7f010006;
        public static final int colorScheme = 0x7f010007;
        public static final int finishPrimaryWithSecondary = 0x7f010008;
        public static final int finishSecondaryWithPrimary = 0x7f010009;
        public static final int font = 0x7f01000a;
        public static final int fontProviderAuthority = 0x7f01000b;
        public static final int fontProviderCerts = 0x7f01000c;
        public static final int fontProviderFetchStrategy = 0x7f01000d;
        public static final int fontProviderFetchTimeout = 0x7f01000e;
        public static final int fontProviderPackage = 0x7f01000f;
        public static final int fontProviderQuery = 0x7f010010;
        public static final int fontProviderSystemFontFamily = 0x7f010011;
        public static final int fontStyle = 0x7f010012;
        public static final int fontVariationSettings = 0x7f010013;
        public static final int fontWeight = 0x7f010014;
        public static final int imageAspectRatio = 0x7f010015;
        public static final int imageAspectRatioAdjust = 0x7f010016;
        public static final int lStar = 0x7f010017;
        public static final int nestedScrollViewStyle = 0x7f010018;
        public static final int placeholderActivityName = 0x7f010019;
        public static final int primaryActivityName = 0x7f01001a;
        public static final int queryPatterns = 0x7f01001b;
        public static final int scopeUris = 0x7f01001c;
        public static final int secondaryActivityAction = 0x7f01001d;
        public static final int secondaryActivityName = 0x7f01001e;
        public static final int shortcutMatchRequired = 0x7f01001f;
        public static final int splitLayoutDirection = 0x7f010020;
        public static final int splitMinSmallestWidth = 0x7f010021;
        public static final int splitMinWidth = 0x7f010022;
        public static final int splitRatio = 0x7f010023;
        public static final int ttcIndex = 0x7f010024;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 0x7f020000;
        public static final int androidx_core_secondary_text_default_material_light = 0x7f020001;
        public static final int call_notification_answer_color = 0x7f020006;
        public static final int call_notification_decline_color = 0x7f020007;
        public static final int notification_action_color_filter = 0x7f020013;
        public static final int notification_icon_bg_color = 0x7f020014;
    }

    public static final class dimen {
        public static final int browser_actions_context_menu_max_width = 0x7f030000;
        public static final int browser_actions_context_menu_min_padding = 0x7f030001;
        public static final int compat_button_inset_horizontal_material = 0x7f030002;
        public static final int compat_button_inset_vertical_material = 0x7f030003;
        public static final int compat_button_padding_horizontal_material = 0x7f030004;
        public static final int compat_button_padding_vertical_material = 0x7f030005;
        public static final int compat_control_corner_material = 0x7f030006;
        public static final int notification_action_icon_size = 0x7f030009;
        public static final int notification_action_text_size = 0x7f03000a;
        public static final int notification_big_circle_margin = 0x7f03000b;
        public static final int notification_content_margin_start = 0x7f03000c;
        public static final int notification_large_icon_height = 0x7f03000d;
        public static final int notification_large_icon_width = 0x7f03000e;
        public static final int notification_main_column_padding_top = 0x7f03000f;
        public static final int notification_media_narrow_margin = 0x7f030010;
        public static final int notification_right_icon_size = 0x7f030011;
        public static final int notification_right_side_padding_top = 0x7f030012;
        public static final int notification_small_icon_background_padding = 0x7f030013;
        public static final int notification_small_icon_size_as_large = 0x7f030014;
        public static final int notification_subtext_size = 0x7f030015;
        public static final int notification_top_pad = 0x7f030016;
        public static final int notification_top_pad_large_text = 0x7f030017;
    }

    public static final class drawable {
        public static final int common_full_open_on_phone = 0x7f040000;
        public static final int launch_background = 0x7f04001e;
        public static final int notification_action_background = 0x7f04001f;
        public static final int notification_bg = 0x7f040020;
        public static final int notification_bg_low = 0x7f040021;
        public static final int notification_bg_low_normal = 0x7f040022;
        public static final int notification_bg_low_pressed = 0x7f040023;
        public static final int notification_bg_normal = 0x7f040024;
        public static final int notification_bg_normal_pressed = 0x7f040025;
        public static final int notification_icon_background = 0x7f040026;
        public static final int notification_oversize_large_icon_bg = 0x7f040027;
        public static final int notification_template_icon_bg = 0x7f040028;
        public static final int notification_template_icon_low_bg = 0x7f040029;
        public static final int notification_tile_bg = 0x7f04002a;
        public static final int notify_panel_notification_icon_bg = 0x7f04002b;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f050000;
        public static final int accessibility_custom_action_0 = 0x7f050001;
        public static final int accessibility_custom_action_1 = 0x7f050002;
        public static final int accessibility_custom_action_10 = 0x7f050003;
        public static final int accessibility_custom_action_11 = 0x7f050004;
        public static final int accessibility_custom_action_12 = 0x7f050005;
        public static final int accessibility_custom_action_13 = 0x7f050006;
        public static final int accessibility_custom_action_14 = 0x7f050007;
        public static final int accessibility_custom_action_15 = 0x7f050008;
        public static final int accessibility_custom_action_16 = 0x7f050009;
        public static final int accessibility_custom_action_17 = 0x7f05000a;
        public static final int accessibility_custom_action_18 = 0x7f05000b;
        public static final int accessibility_custom_action_19 = 0x7f05000c;
        public static final int accessibility_custom_action_2 = 0x7f05000d;
        public static final int accessibility_custom_action_20 = 0x7f05000e;
        public static final int accessibility_custom_action_21 = 0x7f05000f;
        public static final int accessibility_custom_action_22 = 0x7f050010;
        public static final int accessibility_custom_action_23 = 0x7f050011;
        public static final int accessibility_custom_action_24 = 0x7f050012;
        public static final int accessibility_custom_action_25 = 0x7f050013;
        public static final int accessibility_custom_action_26 = 0x7f050014;
        public static final int accessibility_custom_action_27 = 0x7f050015;
        public static final int accessibility_custom_action_28 = 0x7f050016;
        public static final int accessibility_custom_action_29 = 0x7f050017;
        public static final int accessibility_custom_action_3 = 0x7f050018;
        public static final int accessibility_custom_action_30 = 0x7f050019;
        public static final int accessibility_custom_action_31 = 0x7f05001a;
        public static final int accessibility_custom_action_4 = 0x7f05001b;
        public static final int accessibility_custom_action_5 = 0x7f05001c;
        public static final int accessibility_custom_action_6 = 0x7f05001d;
        public static final int accessibility_custom_action_7 = 0x7f05001e;
        public static final int accessibility_custom_action_8 = 0x7f05001f;
        public static final int accessibility_custom_action_9 = 0x7f050020;
        public static final int action_container = 0x7f050021;
        public static final int action_divider = 0x7f050022;
        public static final int action_image = 0x7f050023;
        public static final int action_text = 0x7f050024;
        public static final int actions = 0x7f050025;
        public static final int androidx_window_activity_scope = 0x7f050028;
        public static final int auto = 0x7f05002a;
        public static final int blocking = 0x7f05002b;
        public static final int dark = 0x7f050032;
        public static final int icon = 0x7f050037;
        public static final int icon_group = 0x7f050038;
        public static final int icon_only = 0x7f050039;
        public static final int info = 0x7f05003a;
        public static final int light = 0x7f05003c;
        public static final int line1 = 0x7f05003d;
        public static final int line3 = 0x7f05003e;
        public static final int locale = 0x7f05003f;
        public static final int none = 0x7f050041;
        public static final int notification_background = 0x7f050043;
        public static final int notification_main_column = 0x7f050044;
        public static final int notification_main_column_container = 0x7f050045;
        public static final int report_drawn = 0x7f050046;
        public static final int right_icon = 0x7f050047;
        public static final int right_side = 0x7f050048;
        public static final int tag_accessibility_pane_title = 0x7f05004e;
        public static final int tag_on_apply_window_listener = 0x7f05004f;
        public static final int tag_unhandled_key_event_manager = 0x7f050055;
        public static final int tag_unhandled_key_listeners = 0x7f050056;
        public static final int tag_window_insets_animation_callback = 0x7f050057;
        public static final int text = 0x7f050058;
        public static final int text2 = 0x7f050059;
        public static final int time = 0x7f05005a;
        public static final int title = 0x7f05005b;
        public static final int view_tree_lifecycle_owner = 0x7f05005c;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f05005d;
        public static final int view_tree_saved_state_registry_owner = 0x7f05005e;
        public static final int view_tree_view_model_store_owner = 0x7f05005f;
    }

    public static final class integer {
        public static final int google_play_services_version = 0x7f060000;
        public static final int status_bar_notification_info_maxnum = 0x7f060001;
    }

    public static final class layout {
        public static final int custom_dialog = 0x7f070002;
        public static final int notification_action = 0x7f070005;
        public static final int notification_action_tombstone = 0x7f070006;
        public static final int notification_template_custom_big = 0x7f070007;
        public static final int notification_template_icon_group = 0x7f070008;
        public static final int notification_template_part_chronometer = 0x7f070009;
        public static final int notification_template_part_time = 0x7f07000a;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f080000;
    }

    public static final class raw {
        public static final int firebase_common_keep = 0x7f090000;
    }

    public static final class string {
        public static final int android_credentials_TYPE_PASSWORD_CREDENTIAL = 0x7f0a0000;
        public static final int androidx_credentials_TYPE_PUBLIC_KEY_CREDENTIAL = 0x7f0a0001;
        public static final int androidx_startup = 0x7f0a0002;
        public static final int call_notification_answer_action = 0x7f0a0003;
        public static final int call_notification_answer_video_action = 0x7f0a0004;
        public static final int call_notification_decline_action = 0x7f0a0005;
        public static final int call_notification_hang_up_action = 0x7f0a0006;
        public static final int call_notification_incoming_text = 0x7f0a0007;
        public static final int call_notification_ongoing_text = 0x7f0a0008;
        public static final int call_notification_screening_text = 0x7f0a0009;
        public static final int common_google_play_services_enable_button = 0x7f0a000a;
        public static final int common_google_play_services_enable_text = 0x7f0a000b;
        public static final int common_google_play_services_enable_title = 0x7f0a000c;
        public static final int common_google_play_services_install_button = 0x7f0a000d;
        public static final int common_google_play_services_install_text = 0x7f0a000e;
        public static final int common_google_play_services_install_title = 0x7f0a000f;
        public static final int common_google_play_services_notification_channel_name = 0x7f0a0010;
        public static final int common_google_play_services_notification_ticker = 0x7f0a0011;
        public static final int common_google_play_services_unknown_issue = 0x7f0a0012;
        public static final int common_google_play_services_unsupported_text = 0x7f0a0013;
        public static final int common_google_play_services_update_button = 0x7f0a0014;
        public static final int common_google_play_services_update_text = 0x7f0a0015;
        public static final int common_google_play_services_update_title = 0x7f0a0016;
        public static final int common_google_play_services_updating_text = 0x7f0a0017;
        public static final int common_google_play_services_wear_update_text = 0x7f0a0018;
        public static final int common_open_on_phone = 0x7f0a0019;
        public static final int copy_toast_msg = 0x7f0a001c;
        public static final int gcm_defaultSenderId = 0x7f0a0020;
        public static final int google_api_key = 0x7f0a0021;
        public static final int google_app_id = 0x7f0a0022;
        public static final int google_crash_reporting_api_key = 0x7f0a0023;
        public static final int google_storage_bucket = 0x7f0a0024;
        public static final int project_id = 0x7f0a0025;
        public static final int status_bar_notification_info_overflow = 0x7f0a0026;
    }

    public static final class style {
        public static final int LaunchTheme = 0x7f0b0000;
        public static final int NormalTheme = 0x7f0b0001;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0b0003;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0b0005;
        public static final int Theme_Hidden = 0x7f0b0007;
        public static final int Theme_PlayCore_Transparent = 0x7f0b0008;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0b0009;
        public static final int Widget_Compat_NotificationActionText = 0x7f0b000a;
    }

    public static final class xml {
        public static final int flutter_image_picker_file_paths = 0x7f0d0000;
        public static final int image_share_filepaths = 0x7f0d0001;
    }
}
